"use strict";

// Lesson 03 exercise: Strings and numbers
// In your exercise repository, create a branch named `lesson-03-exercise` and switch to it,
// then open `lesson-03.js`, where the questions wait as comments. Work beneath each question
// in order.

// TODO: Part one.
// Declare variables for a shop name, an opening hour, and a closing hour, then log one
// welcoming sentence built as a single template literal that uses all three.
const shopName = "Kelnad Agency";
const openingHour = 6;
const closingHour = 4;

console.log(
  `${shopName} opens at ${openingHour}am and closes at ${closingHour}pm.`,
);

// TODO: Part two.
// The file provides a messy string with surplus spaces at both ends, the wrong case, and one
// word that needs replacing. Apply the methods from this lesson, chained or in sequence, to
// log the cleaned version, and add a comment naming each method you used and the job it
// performed.

// * The provided messy string:
const messy = "   Maison   Sarah, fresh bread daily   ";
console.log(messy.replace("daily", "hourly").trim().toLowerCase());

// Used the trim method to get rid of whitespace.
// Used the toLowerCase method to correct the case.
// Used the replace method to replace word "daily" to "hourly".

// TODO: Part three.
// Using the provided product string, log its length, the position at which a given word
// begins, and a slice containing exactly that word. Then split the provided comma-separated
// list and log the resulting pieces.

// * The provided product string and comma-separated list:
const product = "Sourdough Loaf, whole grain";
const flavorList = "rye,spelt,wheat,olive";

console.log(product.length);
console.log(product.indexOf("Loaf"));
console.log(product.slice(10, 14));

console.log(flavorList.split(","));

// TODO: Part four.
// From the net price and tax rate in the file, calculate the final price and log it inside a
// template literal, formatted to two decimal places. Add a comment explaining why the
// formatting step must come last.

// * The provided net price and tax rate:
const netPrice = 4.0;
const taxRate = 0.07;

let finalPrice = netPrice + netPrice * taxRate;
console.log(`${finalPrice.toFixed(2)}`);

// Formatting step must come last because the toFixed methods always returns a string hence can result in miscalculation when used early.

// TODO: Part five.
// Using the random recipe from this lesson, log a random whole number from 1 to 6. Then adapt
// the recipe to produce a number from 10 to 20, and explain your adaptation in a comment.
console.log(Math.floor(Math.random() * 6) + 1);

console.log(Math.floor(Math.random() * 11) + 10);

// The floor method turns the decimals generated by the random into a whole number and random starts from 0 to a certain number.
// So adding 1 changes the start point to 1 and makes the end range 7.
// Since the range does not include the end value, it is then 1 to 6. Same applies for range 10 to 20.

// TODO: Part six.
// Open the MDN String reference, choose one method this lesson did not cover, and use it
// correctly on a string of your choice. In a comment, cite the method's name and describe what
// it does in one sentence of your own words.

const sentence = "An apple a day keeps the doctor away.";
console.log(sentence.valueOf());
// The valueOf() method of String values returns the value of the string as a string datatype.

// TODO: Part seven.
// Two classic exercises close the lesson. First, build a username generator: from a first name
// and a last name held in variables, produce a lowercase username in the pattern of first
// initial followed by full last name, such as mmustermann. Second, write a mad-libs story:
// declare four variables, an adjective, a noun, a verb, and a place, and log one short,
// ridiculous story built from a single template literal that uses all four.
let firstName = "Kekeli";
let lastName = "Norgbey";

const username = (firstName.slice(0, 1) + lastName).toLowerCase();
console.log(username);

const adjective = "spicy";
const noun = "Ants";
const verb = "cook";
const place = "Bad Nauheim";

console.log(`${noun} ${verb} ${adjective} noodles in ${place}.`);

// TODO: Save deliberately, commit with a clear message, push the branch, and open a pull request
// into main.
// TODO: Submit the link to the pull request for review.
